### ISSUE TITLE
Šumniki v imenih datotek

### ISSUE THREAD

**Issue by jaanos** [TomasRode/APPR-2018-19#1]
V izogib morebitnim težavam svetujem, da v imenih datotek ne uporabljaš šumnikov in drugih posebnih znakov (pa tudi presledkom se raje izogibaj). Tako predlagam, da preimenuješ datoteko `podatki/WorldBankData_izobraževanje.csv`.

**Comment by TomasRode** [comment]
Popravil, hvala
